import "./globals.css";

import type { Metadata } from "next";
import { NavigationBar, MenuItem } from "@/components/UI/NavigationBar";

// TODO: update tailwind imported fonts w/localFonts
// see layout.tsx.orig

export const metadata: Metadata = {
    title: "NIAGADS Open Access API",
    //description: "Generated by create next app",
};

const NAV_MENU_ITEMS: MenuItem[] = [
    { label: "API Documentation", href: "/docs" },
    { label: "FILER", href: "https://tf.lisanwanglab.org/FILER/" },
    { label: "GenomicsDB", href: "https://www.niagads.org/genomics" },
    { label: "ADVP", href: "https://advp.niagads.org" },
];

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en">
                <body className={`m-0 antialiased`}>
                    <header>
                        <NavigationBar
                            variant="primary"
                            brand={{
                                label: "NIAGADS",
                                href: "https://www.niagads.org",
                            }}
                            menuItems={NAV_MENU_ITEMS}></NavigationBar>
                    </header>
                    {children}
                </body>
            </html>
        </>
    );
}
